security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
  user:
    name: zhang
    password: 123

logging:
  level:
    org.springframework.security: DEBUG

